### PR TITLE
Fixed unknown bug in inflateRaw

### PR DESCRIPTION
**Pull request by L1quidH2O**
inflateRaw was causing problems for me where it would return a wrong length buffer (but with the correct data).
Ive minified a version of inflateRaw from [UZIP.js](https://github.com/photopea/UZIP.js/) and removed unused code leading to a correct and shorter inflateRaw function.

### CODE REVIEW

**Comment by photopea** [comment]
Hi, could you show me a PNG image which can not be parsed by the latest version of UPNG.js?

**Comment by L1quidH2O** [comment]
I was using it for something unrelated to UPNG.js, and since I do not know how to replicate it, I've just thrown the entire zlibbed data into a PNG.

It seems `IDAT` is safe as it passes a second parameter to `inflateRaw`, which the function uses to determine length.
although `iCCP`, `zTXt`, and `iTXt` are not.

Here I've placed my file in the `zTXt` chunk. It is supposed to be ~760kb, but instead returns ~120kb.

zTXt

**Comment by photopea** [comment]
But could you show me that PNG file?

**Comment by L1quidH2O** [comment]
The PNG file is the small batman pic in my previous comment: https://github.com/photopea/UPNG.js/assets/85402740/41885607-8954-498d-af95-a76ff255f50e

**Comment by photopea** [comment]
ok, I have uploaded a new version.

**Pull request closed without merging**
